Assert if trying to run command that doesn't exist
The current implementation is not very easy to debug when it tries to run a
command that doesn't exist, so this adds a check to determine if the
command exists before running it.

If something is missing (e.g. meson), then the following message will be
printed:

> AssertionError: ERROR: Tried to run a command that doesn't exist: meson